const kDIRECTORY = [
  { name: "Droid Sans",        subsets: "latin", regular: true, bold: true,  italic: false, bolditalic: false, extra: ""},
  { name: "Lobster",           subsets: "latin", regular: true, bold: false, italic: false, bolditalic: false, extra: "" },
  { name: "Droid Serif",       subsets: "latin", regular: true, bold: true,  italic: true,  bolditalic: true,  extra: "" },
  { name: "Yanone Kaffeesatz", subsets: "latin", regular: true, bold: true,  italic: false, bolditalic: false, extra: "extralight,light" },
  { name: "Nobile",            subsets: "latin", regular: true, bold: true,  italic: true,  bolditalic: true,  extra: "" },
  { name: "Reenie Beanie",     subsets: "latin", regular: true, bold: false, italic: false, bolditalic: false, extra: "" },
  { name: "Molengo",           subsets: "latin", regular: true, bold: false, italic: false, bolditalic: false, extra: "" },
  { name: "OFL Sorts Mill Goudy TT", subsets: "latin", regular: true, bold: false, italic: true, bolditalic: false, extra: "" },
  { name: "PT Sans",           subsets: "latin,cyrillic", regular: true, bold: true,  italic: true,  bolditalic: true,  extra: "" },
  { name: "PT Sans Caption",   subsets: "latin,cyrillic", regular: true, bold: true,  italic: false,  bolditalic: false,  extra: "" },
  { name: "PT Sans Narrow",    subsets: "latin,cyrillic", regular: true, bold: true,  italic: false,  bolditalic: false,  extra: "" },
  { name: "Tangerine",         subsets: "latin", regular: true, bold: true,  italic: false, bolditalic: false, extra: ""},
  { name: "Vollkorn",          subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "Cantarell",         subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "Inconsolata",       subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Cardo",             subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Crimson Text",      subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Neucha",            subsets: "latin,cyrillic", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Droid Sans Mono",   subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Arvo",              subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "Neuton",            subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Old Standard TT",   subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: false, extra: ""},
  { name: "IM Fell DW Pica",   subsets: "latin", regular: true, bold: false,  italic: true, bolditalic: false, extra: ""},
  { name: "IM Fell English",   subsets: "latin", regular: true, bold: false,  italic: true, bolditalic: false, extra: ""},
  { name: "IM Fell English SC", subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "IM Fell DW Pica SC", subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "IM Fell Double Pica SC", subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "IM Fell Double Pica", subsets: "latin", regular: true, bold: false,  italic: true, bolditalic: false, extra: ""},
  { name: "IM Fell Great Primer SC", subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "IM Fell Great Primer", subsets: "latin", regular: true, bold: false,  italic: true, bolditalic: false, extra: ""},
  { name: "IM Fell French Canon", subsets: "latin", regular: true, bold: false,  italic: true, bolditalic: false, extra: ""},
  { name: "IM Fell French Canon SC", subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Cuprum",            subsets: "latin,cyrillic", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Philosopher",       subsets: "latin,cyrillic", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Josefin Sans",  subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: true, extra: "100,100italic,light,regularitalic,600,600italic"},
  { name: "Tinos",         subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "Arimo",         subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "Josefin Slab",  subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: true, extra: "100,100italic,light,regularitalic,600,600italic"},
  { name: "Cousine",       subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "Allerta Stencil",   subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "UnifrakturMaguntia",   subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Allerta",       subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Bentham",       subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Geo",           subsets: "latin", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Puritan",       subsets: "latin", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "GFS Neohellenic", subsets: "greek", regular: true, bold: true,  italic: true, bolditalic: true, extra: ""},
  { name: "GFS Didot",     subsets: "greek", regular: true, bold: false,  italic: false, bolditalic: false, extra: ""},
  { name: "Hanuman",       subsets: "khmer", regular: true, bold: true,  italic: false, bolditalic: false, extra: ""}
];

const kPREVIEW_URL = "http://code.google.com/webfonts/preview#font-family=";
const kLOADER_URL = "http://fonts.googleapis.com/css?family=";

