  <panel id="AutoInsertTableSheetPopup">
    <spacer style="height: 1em"/>
    <hbox>
      <spacer style="width: 1em"/>
      <grid id="AutoInsertTableSizeSelector">
        <columns><column flex="1"/><column/><column flex="1"/></columns>
        <rows id="AutoInsertTableSizeSelectorRows">
          <row>
            <spacer/>
            <hbox>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r1c1" class="selected"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r1c2" class="selected"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r1c3"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r1c4"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r1c5"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r1c6"/>
            </hbox>
            <spacer/>
          </row>
          <row>
            <spacer/>
            <hbox>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r2c1" class="selected"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r2c2" class="selected"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r2c3"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r2c4"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r2c5"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r2c6"/>
            </hbox>
            <spacer/>
          </row>
          <row>
            <spacer/>
            <hbox>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r3c1"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r3c2"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r3c3"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r3c4"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r3c5"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r3c6"/>
            </hbox>
            <spacer/>
          </row>
          <row>
            <spacer/>
            <hbox>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r4c1"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r4c2"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r4c3"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r4c4"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r4c5"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r4c6"/>
            </hbox>
            <spacer/>
          </row>
          <row>
            <spacer/>
            <hbox>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r5c1"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r5c2"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r5c3"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r5c4"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r5c5"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r5c6"/>
            </hbox>
            <spacer/>
          </row>
          <row>
            <spacer/>
            <hbox>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r6c1"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r6c2"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r6c3"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r6c4"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r6c5"/>
              <label onmouseover="AutoInsertTable.selectArea(this)" onclick="AutoInsertTable.selectSize(this)" value=" " id="AutoInsertTable_r6c6"/>
            </hbox>
            <spacer/>
          </row>
        </rows>
      </grid>
      <spacer style="width: 1em" onmouseover="AutoInsertTable.increaseSize(true, false)"/>
    </hbox>
    <hbox align="center" onmouseover="AutoInsertTable.increaseSize(false, true)"
          style="opacity: 1;">
      <spacer class="spacer" flex="1"/>
      <label id="AutoInsertTableSizeLabel" value="2 x 2"/>
      <spacer class="spacer" flex="1"/>
    </hbox>
  </panel>
