

#include "nsISupports.idl"
#include "domstubs.idl"

interface nsIDOMNode;

/**
 *
 */
[scriptable, uuid(64BB96CF-3ECD-4691-B468-AACEDF33D951)]
interface diIStyleAttrChangeTxn: nsISupports
{


  nsIDOMNode getNode();
};

