const kHTML_TRANSITIONAL = "resource://gre/res/html_transitional.html";
const kHTML_STRICT = "resource://gre/res/html_strict.html";
const kXHTML_TRANSITIONAL = "resource://gre/res/xhtml_transitional.xhtml";
const kXHTML_STRICT = "resource://gre/res/xhtml_strict.xhtml";
const kHTML5 = "resource://gre/res/html5.html";
const kXHTML5 = "resource://gre/res/xhtml5.xhtml";
const kXHTML11 = "resource://gre/res/xhtml11.xhtml";
const kPOLYGLOT = "resource://gre/res/polyglot.xhtml";
