var kHTML_TRANSITIONAL = "resource://gre/res/html_transitional.html";
var kHTML_STRICT = "resource://gre/res/html_strict.html";
var kXHTML_TRANSITIONAL = "resource://gre/res/xhtml_transitional.xhtml";
var kXHTML_STRICT = "resource://gre/res/xhtml_strict.xhtml";
var kHTML5 = "resource://gre/res/html5.html";
var kXHTML5 = "resource://gre/res/xhtml5.xhtml";
var kXHTML11 = "resource://gre/res/xhtml11.xhtml";
var kPOLYGLOT = "resource://gre/res/polyglot.xhtml";
