/* TEXT-ALIGN */

#lefttextalignButton {
  list-style-image: url("chrome://bluegriffon/skin/formatToolbar/align-left.png");
}

#righttextalignButton {
  list-style-image: url("chrome://bluegriffon/skin/formatToolbar/align-right.png");
}

#centertextalignButton {
  list-style-image: url("chrome://bluegriffon/skin/formatToolbar/align-center.png");
}

#justifytextalignButton {
  list-style-image: url("chrome://bluegriffon/skin/formatToolbar/align-justify.png");
}

#lefttextalignButton .toolbarbutton-text,
#righttextalignButton .toolbarbutton-text,
#centertextalignButton .toolbarbutton-text,
#justifytextalignButton .toolbarbutton-text {
  display: none;
}

